---
apiVersion: batch/v1
kind: Job
metadata:
  name: nanochat-02-tokenizer
  namespace: nanochat
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: nanochat
        image: quay.io/surajd/nanochat:latest
        args: ["tokenizer"]
        resources:
          limits:
            memory: "32Gi"
            cpu: "16"
          requests:
            memory: "16Gi"
            cpu: "8"
        volumeMounts:
        - name: nanochat-data
          mountPath: /data/nanochat
      volumes:
      - name: nanochat-data
        persistentVolumeClaim:
          claimName: nanochat-data
      nodeSelector:
        node.kubernetes.io/instance-type: Standard_ND96isr_H100_v5
