---
apiVersion: v1
kind: Namespace
metadata:
  name: nanochat
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanochat-data
  namespace: nanochat
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi-premium
  resources:
    requests:
      storage: 256Gi
